### ISSUE TITLE
Air Quality Monitor

### ISSUE THREAD

**Issue by Rutuj-Runwal** [KrishGaur1354/Python-Projects-for-Beginners#4]
A Python based GUI application that shows the air quality index data of a particular city.
The user have to enter a city and the python application will show them the populiation and air quality index in that city.

**Comment by Rutuj-Runwal** [comment]
@KrishGaur1354  Please assign this to me.I would love to contribute to your project under hacktoberfest.

**Comment by KrishGaur1354** [comment]
Assigned

**Comment by Rutuj-Runwal** [comment]
> Assigned

Thanks also please do add the "hacktoberfest" and "hacktoberfest2022" labels for this so it makes it easier for the system

**Comment by Rutuj-Runwal** [comment]
@KrishGaur1354 In the pull request #10  if you can add the exact label: "hacktoberfest-accepted" otherwise hacktober team is unable to check out your wonderful project please look into it
